import { Setting } from "obsidian";
import type { ObsidianGitSettings } from "src/types";
import type { AppearanceSectionContext } from "../renderContext";

export const renderAppearanceSection: (
    context: AppearanceSectionContext
) => void = (context) => {
    const { containerEl, plugin, refreshDisplayWithDelay } = context;
    new Setting(containerEl).setName("Interface & notifications").setHeading();

    if (plugin.useSimpleGit) {
        new Setting(containerEl)
            .setName("Diff view style")
            .setDesc(
                'Set the style for the diff view. Note that the actual diff in "Split" mode is not generated by Git, but the editor itself instead so it may differ from the diff generated by Git. One advantage of this is that you can edit the text in that view.'
            )
            .addDropdown((dropdown) => {
                const options: Record<
                    ObsidianGitSettings["diffStyle"],
                    string
                > = {
                    split: "Split",
                    git_unified: "Unified",
                };
                dropdown.addOptions(options);
                dropdown.setValue(plugin.settings.diffStyle);
                dropdown.onChange(async (option) => {
                    plugin.settings.diffStyle =
                        option as ObsidianGitSettings["diffStyle"];
                    await plugin.saveSettings();
                });
            });
    }

    new Setting(containerEl)
        .setName("Disable informative notifications")
        .setDesc(
            "Disable informative notifications for git operations to minimize distraction (refer to status bar for updates)."
        )
        .addToggle((toggle) =>
            toggle
                .setValue(plugin.settings.disablePopups)
                .onChange(async (value) => {
                    plugin.settings.disablePopups = value;
                    refreshDisplayWithDelay();
                    await plugin.saveSettings();
                })
        );

    new Setting(containerEl)
        .setName("Disable error notifications")
        .setDesc(
            "Disable error notifications of any kind to minimize distraction (refer to status bar for updates)."
        )
        .addToggle((toggle) =>
            toggle
                .setValue(!plugin.settings.showErrorNotices)
                .onChange(async (value) => {
                    plugin.settings.showErrorNotices = !value;
                    await plugin.saveSettings();
                })
        );

    if (!plugin.settings.disablePopups) {
        new Setting(containerEl)
            .setName("Hide notifications for no changes")
            .setDesc(
                "Don't show notifications when there are no changes to commit or push."
            )
            .addToggle((toggle) =>
                toggle
                    .setValue(plugin.settings.disablePopupsForNoChanges)
                    .onChange(async (value) => {
                        plugin.settings.disablePopupsForNoChanges = value;
                        await plugin.saveSettings();
                    })
            );
    }

    new Setting(containerEl)
        .setName("Show status bar")
        .setDesc("Obsidian must be restarted for the changes to take effect.")
        .addToggle((toggle) =>
            toggle
                .setValue(plugin.settings.showStatusBar)
                .onChange(async (value) => {
                    plugin.settings.showStatusBar = value;
                    await plugin.saveSettings();
                })
        );

    new Setting(containerEl)
        .setName("File menu integration")
        .setDesc(
            "Add Git actions, file history, and per-file Encrypt/Decrypt actions to supported file context menus."
        )
        .addToggle((toggle) =>
            toggle
                .setValue(plugin.settings.showFileMenu)
                .onChange(async (value) => {
                    plugin.settings.showFileMenu = value;
                    await plugin.saveSettings();
                })
        );

    new Setting(containerEl)
        .setName("Show branch status bar")
        .setDesc("Obsidian must be restarted for the changes to take effect.")
        .addToggle((toggle) =>
            toggle
                .setValue(plugin.settings.showBranchStatusBar)
                .onChange(async (value) => {
                    plugin.settings.showBranchStatusBar = value;
                    await plugin.saveSettings();
                })
        );

    new Setting(containerEl)
        .setName("Show the count of modified files in the status bar")
        .setDesc(
            "Show the number of modified files in the status bar. No restart required."
        )
        .addToggle((toggle) =>
            toggle
                .setValue(plugin.settings.changedFilesInStatusBar)
                .onChange(async (value) => {
                    plugin.settings.changedFilesInStatusBar = value;
                    await plugin.saveSettings();
                })
        );
};
