import { Platform } from "obsidian";
import type { ObsidianGitSettings } from "./types";
export const DATE_FORMAT = "YYYY-MM-DD";
export const DATE_TIME_FORMAT_MINUTES = `${DATE_FORMAT} HH:mm`;
export const DATE_TIME_FORMAT_SECONDS = `${DATE_FORMAT} HH:mm:ss`;

export const GIT_LINE_AUTHORING_MOVEMENT_DETECTION_MINIMAL_LENGTH = 40;

export const CONFLICT_OUTPUT_FILE = "conflict-files-obsidian-git.md";

export const DEFAULT_SETTINGS: ObsidianGitSettings = {
    commitMessage: "vault backup: {{date}}",
    autoCommitMessage: "vault backup: {{date}}",
    commitMessageScript: "",
    commitDateFormat: DATE_TIME_FORMAT_SECONDS,
    autoSaveInterval: 0,
    autoPushInterval: 0,
    autoPullInterval: 0,
    autoPullOnBoot: false,
    autoCommitOnlyStaged: false,
    disablePush: false,
    pullBeforePush: true,
    disablePopups: false,
    showErrorNotices: true,
    disablePopupsForNoChanges: false,
    listChangedFilesInMessageBody: false,
    showStatusBar: true,
    updateSubmodules: false,
    syncMethod: "merge",
    mergeStrategy: "none",
    customMessageOnAutoBackup: false,
    autoBackupAfterFileChange: false,
    treeStructure: false,
    refreshSourceControl: Platform.isDesktopApp,
    basePath: "",
    differentIntervalCommitAndPush: false,
    changedFilesInStatusBar: false,
    showedMobileNotice: false,
    refreshSourceControlTimer: 7000,
    showBranchStatusBar: true,
    setLastSaveToLastCommit: false,
    submoduleRecurseCheckout: false,
    gitDir: "",
    showFileMenu: true,
    showExplorerEncryptionIndicator: true,
    authorInHistoryView: "hide",
    dateInHistoryView: false,
    diffStyle: "split",
    hunks: {
        showSigns: false,
        hunkCommands: false,
        statusBar: "disabled",
    },
    lineAuthor: {
        show: false,
        followMovement: "inactive",
        authorDisplay: "initials",
        showCommitHash: false,
        dateTimeFormatOptions: "date",
        dateTimeFormatCustomString: DATE_TIME_FORMAT_MINUTES,
        dateTimeTimezone: "viewer-local",
        coloringMaxAge: "1y",
        // colors were picked via:
        // https://color.adobe.com/de/create/color-accessibility
        colorNew: { r: 255, g: 150, b: 150 },
        colorOld: { r: 120, g: 160, b: 255 },
        textColorCss: "var(--text-muted)", //  more pronounced than line numbers, but less than the content text
        ignoreWhitespace: false,
        gutterSpacingFallbackLength: 5,
    },

    // ── Hybrid Git Vault defaults ──────────────────────────────────────────
    // Default to simple mode on mobile, advanced on desktop
    syncMode: Platform.isMobileApp ? "simple" : "advanced",
    // Default to the GitHub API backend on mobile (no system Git required), git on desktop
    activeSyncProvider: Platform.isMobileApp ? "github" : "git",
    // API backends – populated by the user in Settings.
    // Tokens are stored in Obsidian secret storage, not synced plugin settings.
    // TODO(sync-security): evaluate desktop keychain integration and per-session
    // prompting on mobile as optional hardened modes on top of secretStorage.
    githubToken: "",
    githubOwner: "",
    githubRepo: "",
    githubBranch: "main",
    gitlabBaseUrl: "https://gitlab.com/api/v4",
    gitlabProjectId: "",
    gitlabBranch: "main",
    giteaBaseUrl: "",
    giteaOwner: "",
    giteaRepo: "",
    giteaBranch: "main",
    trackedDirectory: "",
    syncExcludePaths: [".DS_Store", "Thumbs.db", "*~"],
    apiEncryptionEnabled: false,
    apiEncryptionPassphraseFingerprint: "",
    apiEncryptionPassphraseRepoFingerprint: "",
    // Conflict resolution
    conflictResolutionStrategy: "manual",
    // Smart triggers
    syncOnFileChange: false,
    syncOnFileChangeDebounce: 5000,
    syncOnClose: false,
    syncOnNetworkReconnect: false,
    syncOnIdleMinutes: -1,
    lastSyncedRepoFingerprint: "",
    apiSyncManifestThreshold: 20000,
    apiSyncManifestSampleSize: 1000,
    apiSyncManifestBloomFpRate: 0.01,
    lastSyncManifestIsSummary: false,
    vaultBootstrapPending: false,
    vaultBootstrapHardeningFailure: null,
};

export const SOURCE_CONTROL_VIEW_CONFIG = {
    type: "git-view",
    name: "Source Control",
    icon: "git-pull-request",
};

export const HISTORY_VIEW_CONFIG = {
    type: "git-history-view",
    name: "History",
    icon: "history",
};

export const SPLIT_DIFF_VIEW_CONFIG = {
    type: "split-diff-view",
    name: "Diff view",
    icon: "diff",
};
export const DIFF_VIEW_CONFIG = {
    type: "diff-view",
    name: "Diff View",
    icon: "git-pull-request",
};

export const SYNC_METADATA_VIEW_CONFIG = {
    type: "sync-metadata-view",
    name: "Sync Metadata",
    icon: "info",
};

export const DEFAULT_WIN_GIT_PATH = "C:\\Program Files\\Git\\cmd\\git.exe";
// askpass helper removed — not tracked in source

/**
 * Copied from https://github.com/sindresorhus/binary-extensions/blob/main/binary-extensions.json
 */
export const BINARY_EXTENSIONS = [
    "3dm",
    "3ds",
    "3g2",
    "3gp",
    "7z",
    "a",
    "aac",
    "adp",
    "afdesign",
    "afphoto",
    "afpub",
    "ai",
    "aif",
    "aiff",
    "alz",
    "ape",
    "apk",
    "appimage",
    "ar",
    "arj",
    "asf",
    "au",
    "avi",
    "bak",
    "baml",
    "bh",
    "bin",
    "bk",
    "bmp",
    "btif",
    "bz2",
    "bzip2",
    "cab",
    "caf",
    "cgm",
    "class",
    "cmx",
    "cpio",
    "cr2",
    "cur",
    "dat",
    "dcm",
    "deb",
    "dex",
    "djvu",
    "dll",
    "dmg",
    "dng",
    "doc",
    "docm",
    "docx",
    "dot",
    "dotm",
    "dra",
    "DS_Store",
    "dsk",
    "dts",
    "dtshd",
    "dvb",
    "dwg",
    "dxf",
    "ecelp4800",
    "ecelp7470",
    "ecelp9600",
    "egg",
    "eol",
    "eot",
    "epub",
    "exe",
    "f4v",
    "fbs",
    "fh",
    "fla",
    "flac",
    "flatpak",
    "fli",
    "flv",
    "fpx",
    "fst",
    "fvt",
    "g3",
    "gh",
    "gif",
    "graffle",
    "gz",
    "gzip",
    "h261",
    "h263",
    "h264",
    "icns",
    "ico",
    "ief",
    "img",
    "ipa",
    "iso",
    "jar",
    "jpeg",
    "jpg",
    "jpgv",
    "jpm",
    "jxr",
    "key",
    "ktx",
    "lha",
    "lib",
    "lvp",
    "lz",
    "lzh",
    "lzma",
    "lzo",
    "m3u",
    "m4a",
    "m4v",
    "mar",
    "mdi",
    "mht",
    "mid",
    "midi",
    "mj2",
    "mka",
    "mkv",
    "mmr",
    "mng",
    "mobi",
    "mov",
    "movie",
    "mp3",
    "mp4",
    "mp4a",
    "mpeg",
    "mpg",
    "mpga",
    "mxu",
    "nef",
    "npx",
    "numbers",
    "nupkg",
    "o",
    "odp",
    "ods",
    "odt",
    "oga",
    "ogg",
    "ogv",
    "otf",
    "ott",
    "pages",
    "pbm",
    "pcx",
    "pdb",
    "pdf",
    "pea",
    "pgm",
    "pic",
    "png",
    "pnm",
    "pot",
    "potm",
    "potx",
    "ppa",
    "ppam",
    "ppm",
    "pps",
    "ppsm",
    "ppsx",
    "ppt",
    "pptm",
    "pptx",
    "psd",
    "pya",
    "pyc",
    "pyo",
    "pyv",
    "qt",
    "rar",
    "ras",
    "raw",
    "resources",
    "rgb",
    "rip",
    "rlc",
    "rmf",
    "rmvb",
    "rpm",
    "rtf",
    "rz",
    "s3m",
    "s7z",
    "scpt",
    "sgi",
    "shar",
    "snap",
    "sil",
    "sketch",
    "slk",
    "smv",
    "snk",
    "so",
    "stl",
    "suo",
    "sub",
    "swf",
    "tar",
    "tbz",
    "tbz2",
    "tga",
    "tgz",
    "thmx",
    "tif",
    "tiff",
    "tlz",
    "ttc",
    "ttf",
    "txz",
    "udf",
    "uvh",
    "uvi",
    "uvm",
    "uvp",
    "uvs",
    "uvu",
    "viv",
    "vob",
    "war",
    "wav",
    "wax",
    "wbmp",
    "wdp",
    "weba",
    "webm",
    "webp",
    "whl",
    "wim",
    "wm",
    "wma",
    "wmv",
    "wmx",
    "woff",
    "woff2",
    "wrm",
    "wvx",
    "xbm",
    "xif",
    "xla",
    "xlam",
    "xls",
    "xlsb",
    "xlsm",
    "xlsx",
    "xlt",
    "xltm",
    "xltx",
    "xm",
    "xmind",
    "xpi",
    "xpm",
    "xwd",
    "xz",
    "z",
    "zip",
    "zipx",
];
