name: Build obsidian plugin

on:
    workflow_dispatch:
    push:
        tags:
            - "*"

env:
    PLUGIN_NAME: git-vault

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: pnpm
            - name: Build
              id: build
              run: |
                  pnpm install --ignore-scripts && pnpm rebuild esbuild svelte-preprocess
                  pnpm run build --if-present
                  mkdir ${{ env.PLUGIN_NAME }}
                  cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
                  zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v3
              with:
                  tag_name: ${{ github.ref }}
                  name: ${{ github.ref_name }}
                  generate_release_notes: true
                  draft: false
                  prerelease: false
                  files: |
                      ./${{ env.PLUGIN_NAME }}.zip
                      ./main.js
                      ./manifest.json
                      ./styles.css
